# Generated by Django 3.1 on 2020-11-11 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('seats', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orchestra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('year', models.DateField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.author')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hall')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.performance')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('ipn', models.UUIDField()),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.position')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('sector', models.CharField(max_length=15)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.play')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('actor', models.ForeignKey(limit_choices_to=models.Q(position__title='Actor'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.performance')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='director',
            field=models.ForeignKey(limit_choices_to=models.Q(position__title='Director'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker'),
        ),
        migrations.AddField(
            model_name='performance',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.genre'),
        ),
        migrations.AddField(
            model_name='performance',
            name='orchestra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orchestra'),
        ),
        migrations.CreateModel(
            name='OrchestraMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('musician', models.ForeignKey(limit_choices_to=models.Q(position__title='Musician'), on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
                ('orchestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orchestra')),
            ],
        ),
    ]
