# Generated by Django 3.1 on 2020-11-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
