# Generated by Django 3.1 on 2020-12-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201204_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='signup_confirmation',
        ),
    ]
