# Generated by Django 3.1 on 2020-12-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_customer_signup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='salary',
        ),
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
